## CONFIG SERVER ##
#spring:
#  application:
#    name: vp-user
#  config:
#    import: optional:configserver:http://localhost:8888
#  cloud:
#    config:
#      username: phuocvh
#      password: phuocvh

server:
  port: 8802

spring:
  application:
    name: VP-PRODUCT
  datasource:
    url: jdbc:postgresql://localhost:5432/vp_mall
    username: phuocvh
    password: phuocvh
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
minio:
  endpoint: http://localhost:9000
  bucketName: product
  accessKey: phuocvu511
  secretKey: phuocvu511
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true
#  jackson:
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false
# DEBUB MODE #
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#      type:
#        descriptor:
#          sql:
#            BasicBinder: TRACE

